### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by scoch5** [HCESrl/html-to-vue#14]
Hi @Rigo-m,
i try to install your library in a Nuxt 2.15.7 project but i get this error:

` ERROR  Failed to compile with 2 errors               friendly-errors 16:07:01

These dependencies were not found:                    friendly-errors 16:07:01
                                                      friendly-errors 16:07:01
* html-loader in ./node_modules/vue-to-html/index.js  friendly-errors 16:07:01
* stylus-loader in ./node_modules/vue-to-html/index.js
                                                      friendly-errors 16:07:01
To install them, you can run: npm install --save html-loader stylus-loader`

I try to install these libraries but i get another error.
Can you help me?

Thanks

**Comment by Rigo-m** [comment]
Appena ho un attimo ci guardo

**Comment by scoch5** [comment]
Grazie mille! ✌️

**Comment by Rigo-m** [comment]
https://stackblitz.com/edit/html-to-vue-repro?file=components/TestHtmlToVue.vue

Ho creato una repository di riproduzione, non ho nessun problema.
Forka lo stackblitz e vedi se riesci a riprodurre col minimo di codice possibile, può essere che sia un problema di configurazione del tuo webpack/del tuo progetto.

**Comment by scoch5** [comment]
Ciao Matteo,
ho capito il problema, ho fatto copia incolla dell'esempio su [npm](https://www.npmjs.com/package/html-to-vue) e c'è un refuso, nell'esempio viene importata la libreria 'vue-to-html' e non la tua 'html-to-vue'.
Scusa la perdita di tempo ma non avevo badato alla differenza, ho già visto che hai corretto il readme.

Grazie mille davvero per il supporto!
Daniele

**Comment by Rigo-m** [comment]
Sì e tra l'altro avevo inserito dei `data` in un componente `functional` (che quindi è stateless e non ha i data 😄 )

Grazie a te che mi hai fatto accorgere dell'errore.

Lieto di essere stato utile, buon weekend!
