### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by thejspro** [HCESrl/html-to-vue#18]
https://github.com/HCESrl/html-to-vue/blob/01ce510249f6c390fac76f13430c68391c321bd7/src/ast.js#L60

What is the significance of the current `currentKey`? It seems that the property key name on the `extraComponentsMap` does not  impact how the script works. Or am I missing something here?

If not, perhaps the `extraComponentsMap` could be turned into an array?

**Comment by Rigo-m** [comment]
IIRC (I've made this a long time ago) it's needed to cycle through objects in `extraComponentsMap` and check if any of those matches the conditions it needs to instantiate the vue component in place of the html tag. In hindsight this should be transformed into typescript and it could be made smarter, but it works for now.
